### ISSUE TITLE
Workshop Brain Dump

### ISSUE THREAD

**Issue by anthony-meza** [anthony-meza/WHOI-PO-HPC#1]
Put your ideas here, we can follow up on them in September while we're preparing? @katyabbott

**Comment by anthony-meza** [comment]
- using xesmf to take point-source observations in model fields (can also include a spatial correlation map in this notebook)

**Comment by katyabbott** [comment]
- Common data portals for accessing satellite data, using dask to read in chunked data and how to efficiently perform computations on that data
- tmux 
- mamba

**Comment by katyabbott** [comment]
Might also be nice to add in some helper python scripts based on functions we use pretty regularly that they can import?

**Comment by anthony-meza** [comment]
MAKE SURE PEOPLE HAVE POSEIDON ACCESS

Could have everyone request 5 GBs of memory for workshop purposes?
